# see https://raw.githubusercontent.com/bufbuild/buf-action/refs/heads/main/README.md
name: Buf CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buf:
    name: "Run Buf Action"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Checking for Tagged Release
        run: |
          echo "Current ref: ${{ github.ref }}"
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
              echo "IS_TAGGED_PUSH=true" >> $GITHUB_ENV
          else
              echo "IS_TAGGED_PUSH=false" >> $GITHUB_ENV
          fi

      - name: Debug Information
        run: |
          echo "IS_TAGGED_PUSH: ${{ github.env.IS_TAGGED_PUSH }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Actor: ${{ github.actor }}"

      - name: Setup Buf and Login
        uses: bufbuild/buf-action@v1.0.2
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: "proto"
          push_disable_create: true
          breaking: false
          lint: true
          format: false
          push: false

      - name: Generate Code
        run: buf generate

      - name: Push to Buf Registry
        if: github.env.IS_TAGGED_PUSH == 'true'
        run: |
          echo "Pushing to Buf Registry..."
          buf push proto
          buf registry module info buf.build/zackiles/postgres-proto-schema