# see https://raw.githubusercontent.com/bufbuild/buf-action/refs/heads/main/README.md
name: Buf CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
  IS_TAGGED_PUSH: false # will be overwritten later if this isn't the case

jobs:
  buf:
    name: "Run Buf Action"
    runs-on: "ubuntu-latest"
    container:
      image: rvolosatovs/protoc:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Checking for Tagged Release
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]] && git branch --contains $(git rev-parse HEAD) | grep -q 'main'; then
            echo "IS_TAGGED_PUSH=true" >> $GITHUB_ENV
          else
            echo "IS_TAGGED_PUSH=false" >> $GITHUB_ENV
          fi

      - name: Setup Buf and Login
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: "proto"
          push_disable_create: true
          breaking: false
          lint: true
          format: false
          push: ${{ env.IS_TAGGED_PUSH }}